config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  resources :recipes, only: %i[index show new create update destroy]
  resources :public_recipes, only: %i[index show]
  resources :shopping_lists, path: 'general_shopping_list'
  resources :foods, only: %i[index show new create destroy]
  resources :recipe_foods, only: %i[new create update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :food_id, uniqueness: { scope: :recipe_id }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'foods deleted successfully'
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @user = current_user
    @public_recipes = Recipe.includes([:user]).includes([:recipe_foods]).where(public: true).order(created_at: :desc)
  end

  def show
    @user = current_user
    @public_recipe = Recipe.find(params[:id])
    @public_recipe_foods = RecipeFood.where(recipe_id: params[:id])
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def show; end

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe = current_user.recipes.find(@recipe_food.recipe_id)
    @food = current_user.foods.find(@recipe_food.food_id)
    existing_record = RecipeFood.find_by(recipe_id: @recipe_food.recipe_id, food_id: @recipe_food.food_id)
    if existing_record
      flash[:error] = 'A food item with this name is already added to the recipe.'
      redirect_to recipe_path(@recipe)
      return
    end
    @recipe_food.recipe = @recipe
    @recipe_food.food = @food
    if @recipe_food.save
      flash[:notice] = 'Food added successfully'
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe), notice: 'Food quantity updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(@recipe_food.recipe), notice: 'Food item deleted successfully'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = current_user
    @recipes = @user.recipes.includes(:user, :recipe_foods).order(created_at: :desc)
  end

  def show
    @user = current_user
    @recipe = @user.recipes.find(params[:id])
    @foods = @user.foods.all
    @recipe_food = RecipeFood.new
    @recipe_foods = RecipeFood.where(recipe_id: params[:id]).includes([:food])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      respond_to do |format|
        format.html { redirect_to @recipe }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe deleted successfully'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @ingredients = RecipeFood.group(:food).sum(:quantity)
    @ingredients = @ingredients.select { |ingredient| ingredient.user_id == current_user.id }
    @foods = current_user.foods.all
    @shopping_list = []
    @to_buy = 0
    @total_value = 0

    return if @ingredients.empty? || @foods.empty?

    @ingredients.each do |ingredient|
      @to_buy = ingredient[1] - @foods.find(ingredient[0].id).quantity
      next unless @to_buy.positive?

      @shopping_list.push({
                            name: ingredient[0].name,
                            quantity: @to_buy,
                            price: ingredient[0].price * @to_buy
                          })

      @total_value += ingredient[0].price * @to_buy
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h3>Available Food Items</h3>
<a href="/foods/new">
  <button type="button" class="btn btn-primary mb-3 float-right">Add food</button>
</a>
<table class="table mt-4">
  <thead class="thead-dark">
    <tr>
      <th>Food</th>
      <th>Measurement unit</th>
      <th>Unit price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <%@foods.each do |food|%>
  <tbody>
    <tr class="food-row">
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%= food.price %></td>
      <td> 
        <%= button_to "Delete", "/foods/#{food.id}", method: :delete, data: { confirm: "Are you sure you want to delete this food item?" }, class: "btn btn-danger" %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/foods/new.html.erb
<h3 class= "text-center">New Food</h3>
<%= form_with model: @food, url: foods_path do |form| %>
  <div class="form">
    <div class="form-group">
      <%= form.label :name %> <br>
      <%= form.text_field :name, required: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :measurement_unit %> <br>
      <%= form.text_field :measurement_unit, required: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :price %> <br>
      <%= form.text_field :price, required: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :quantity %> <br>
      <%= form.text_field :quantity, required: true, class: "form-control" %>
    </div>

    <%= form.submit "Add Food", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food & Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Food and Recipe</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "All Foods", foods_path,class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "All Recipes", recipes_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Shopping List", shopping_lists_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
        <span class="text-light"><%= "#{current_user.name}" %></span>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger ml-2" %>
      </nav>
    <% end %>
    <div class='container mt-3'>
      <div>
        <%= yield %>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-success container"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger container"><%= flash[:alert] %></div>
    <% end %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNSbNt0" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/public_recipes/_ingredients.html.erb
<div class="table table-striped mt-5">
  <% if @public_recipe_foods.empty? %>
    <h3 class="text-center">No ingredients has been added by the cook yet.</h3>
  <% else %>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th class="text-center" scope="col">Food Name</th>
          <th class="text-center" scope="col">Quantity</th>
          <th class="text-center" scope="col">Measurement Units</th>
          <th class="text-center" scope="col">Price Per Unit</th>
          <th class="text-center" scope="col">Total Price</th>
        </tr>
      </thead>
      <tbody>
        <% @public_recipe_foods.each do |public_recipe_food| %>
          <tr>
            <td><%= public_recipe_food.food.name %></td>
            <td class="text-center"><%= public_recipe_food.food.quantity %></td>
            <td class="text-center"><%= public_recipe_food.food.measurement_unit %></td>
            <td class="text-center"><%= public_recipe_food.food.price %></td>
            <td class="text-center"><%= public_recipe_food.quantity*public_recipe_food.food.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/public_recipes/index.html.erb
<div class="recipes-container">
  <% if @public_recipes.empty? %>
    <div class="text-center">
      <h1> No public recipes to show. </h1>
    <div>
  <% else %>
    <div class="card-header mb-3">
      <h3>All available public recipes</h3>
    </div>
    <% @public_recipes.each do |public_recipe| %>
      <% @public_recipe_foods = RecipeFood.where(recipe_id: public_recipe.id) %>
      <% @total_price = 0 %>
      <% @public_recipe_foods.each do |public_recipe_food| %>
        <% @total_price += public_recipe_food.quantity*public_recipe_food.food.price %>
      <% end %>
      <div class="card mb-2">
        <% if public_recipe.user_id == current_user.id %>
          <%= link_to recipe_path(public_recipe), style: "text-decoration: none; color: black" do %>
            <div class="d-flex">
              <div class="card-header" style="width: 30%">
                <h4><%= public_recipe.name %></h4>
                <h5>By: <%= public_recipe.user.name %></h5> 
              </div>
              <div class="card-body" style="width: 70%">
                <p class="card-text">Total Food Items: <%= @public_recipe_foods.length %></p>
                <p class="card-text">Total Price: <%= @total_price %></p>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to public_recipe_path(public_recipe), style: "text-decoration: none; color: black" do %>
            <div class="d-flex">
              <div class="card-header" style="width: 30%">
                <h4><%= public_recipe.name %></h4>
                <h5>By: <%= public_recipe.user.name %></h5> 
              </div>
              <div class="card-body" style="width: 70%">
                <p class="card-text">Total Food Items: <%= @public_recipe_foods.length %></p>
                <p class="card-text">Total Price: <%= @total_price %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/public_recipes/show.html.erb
<div class="container mt-3">
  <div class="jumbotron d-flex justify-content-around">
    <div>
      <h3 class="display-6"><%= @public_recipe.name %> by <%= @public_recipe.user.name %></h3>
      <p class="lead">Preparation Time: <%= @public_recipe.preparation_time %> hour</p>
      <p class="lead">Cooking Time: <%= @public_recipe.cooking_time %> hour</p>
      <hr class="my-4">
      <p class='public_recipe-text'><%= @public_recipe.description %></p>
    </div>
    <div>
      <%= form_with model: @public_recipe, class: "form-check form-switch" do |form| %>
        <%= form.check_box :public, class: "form-check-input", readonly: true, style: "pointer-events: none" %>
        <%= form.label :public, class: "form-check-label", for: "flexSwitchCheckDefault" %>
      <% end %>
    </div>
  </div>

  <%= render("ingredients", public_recipe_foods: @public_recipe_foods) %>
</div>

app/views/recipe_foods/_index.html.erb
<div class="table table-striped mt-4">
  <% if @recipe_foods.empty? %>
    <h3 class="text-center">Add ingredients to your recipe</h3>
  <% else %>
    <h4 style = "margin-top: 0" >Ingredients</h4>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th class="text-center">Food Name</th>
          <th class="text-center">Quantity</th>
          <th class="text-center">Value</th>
          <th class="text-center">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe_foods.each do |recipe_food| %>
          <tr>
            <td><%= recipe_food.food.name %></td>
            <td class="text-center">
              <div class="quantity-cell">
                <%= recipe_food.quantity %>
              </div>
              <div class="form-cell hidden">
                <%= form_with model: recipe_food, url: recipe_food_path(recipe_food), method: :patch do |form| %>
                  <%= form.hidden_field :recipe_id, value: recipe_food.recipe_id %>
                  <%= form.hidden_field :food_id, value: recipe_food.food_id %>
                  <div class="input-group mb-2">
                    <%= form.number_field :quantity, class: "form-control text-center", value: recipe_food.quantity, style: "width: 0", required: true, step: "any" %>
                    <div class="input-group-prepend">
                      <div class="input-group-text"><%= recipe_food.food.measurement_unit %></div>
                    </div>
                    <%= form.submit "Update", class: "btn btn-primary" %>
                  </div>
                <% end %>
              </div>
            </td>
            <td class="text-center">$<%= recipe_food.quantity*recipe_food.food.price %></td>
            <td class="text-center d-flex justify-content-center" style="gap: 1em">
              <button type="button" class="btn btn-primary" onclick="toggleQuantityForm(this)">Modify</button>
              <%= button_to "Delete", recipe_food_path(recipe_food), method: :delete, data: { confirm: "Are you sure you want to delete this food item?" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<script>
function toggleQuantityForm(button) {
  const quantityCell = button.closest('tr').querySelector('.quantity-cell');
  const quantityForm = button.closest('tr').querySelector('.form-cell');

  console.log("quantityCell",quantityCell)
  console.log("quantityForm",quantityForm)

  quantityCell.classList.toggle('hidden');
  quantityForm.classList.toggle('hidden');
}
</script>

app/views/recipe_foods/create.html.erb
<h1>RecipeFoods#create</h1>
<p>Find me in app/views/recipe_foods/create.html.erb</p>

app/views/recipe_foods/new.html.erb
<h1>RecipeFoods#new</h1>
<p>Find me in app/views/recipe_foods/new.html.erb</p>

app/views/recipe_foods/show.html.erb
<h1>RecipeFoods#show</h1>
<p>Find me in app/views/recipe_foods/show.html.erb</p>

app/views/recipes/_food_list_modal.html.erb
<div class="modal fade" id="foodsModal" tabindex="-1" role="dialog" aria-labelledby="foodsModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="foodsModalLabel">Select Foods</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @foods.each do |food| %>
          <%= form_with model: @recipe_food, url: recipe_foods_path, class: "form-check" do |form| %>
            <%= form.hidden_field :recipe_id, value: recipe.id %>
            <%= form.hidden_field :food_id, value: food.id %>
            <%= food.name %>
            <div class="input-group mb-2">
              <%= form.number_field :quantity, class: "form-control", placeholder: "Quantity", required: true, step: "any" %>
              <div class="input-group-prepend">
                <div class="input-group-text"><%= food.measurement_unit %></div>
              </div>
            </div>
            <%= form.submit "Add Food", class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<%= link_to new_recipe_path(), class: "d-flex justify-content-center" do %>
  <button class="btn btn-primary">New Recipe</button>
<% end %>

<div class="container mt-5">
  <% if @recipes.empty? %>
    <div class="text-center">
      <h1> No recipes to show </h1>
    <div>
  <% else %>
    <div class="card-header mb-3">
      <h3>My recipes</h3>
    </div>
    <% @recipes.each do |recipe| %>
      <div class="card">
        <div class="d-flex">
          <div class="card-header" style="width: 30%">
            <%= link_to recipe_path(recipe), style: "text-decoration: none; color: black" do %>
              <h4><%= recipe.name %></h4>
            <% end %>
            <div style="width: 30%">
              <%= button_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure you want to delete this food item?" }, class: "btn btn-danger w-75" %>
            </div>
          </div>
          <div style="width: 70%">
            <div class="card-body">
              <p class="card-text"><%= recipe.description %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h3 class="text-center">New Recipe</h3>
<%= form_with model: @recipe, url: recipes_path do |form| %>
  <div class="form">
    <div class="form-group">
      <%= form.label :name %> <br>
      <%= form.text_field :name, required: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :preparation_time_in_hour %> <br>
      <%= form.number_field :preparation_time, required: true, class: "form-control", step: "any" %>
    </div>

    <div class="form-group">
      <%= form.label :cooking_time_in_hour %> <br>
      <%= form.number_field :cooking_time, required: true, class: "form-control", step: "any" %>
    </div>

    <div class="form-group">
      <%= form.label :public %> <br>
      <%= form.check_box :public %>
    </div>

    <div class="form-group">
      <%= form.label :recipe_description %> <br>
      <%= form.text_area :description, required: true, class: "form-control", rows: "3" %>
    </div>
    <%= form.submit "Add Recipe", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div class="container mt-3">
  <div class="jumbotron p-4">
    <h3 class="display-6 text-center"><%= @recipe.name %> by <%= @user.name %></h3>
    <div>
      <div class="row">
        <div class="col-10">
          <p class="lead">Preparation Time: <%= @recipe.preparation_time %> hour</p>
          <p class="lead">Cooking Time: <%= @recipe.cooking_time %> hour</p>
        </div>
        <div class="col-2">
          <%= form_with model: @recipe, url: recipe_path(@recipe), class: "form-check form-switch", method: :patch do |form| %>
            <%= form.check_box :public, class: "form-check-input", role: "switch", id: "flexSwitchCheckDefault", style: "cursor: pointer" %>
            <%= form.label :public, class: "form-check-label", for: "flexSwitchCheckDefault" %>
          <% end %>
        </div>
      </div>
      <hr class="my-4">
      <p class='recipe-text'><%= @recipe.description %></p>
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <%= button_to 'Generate Shopping List', shopping_lists_path, method: :get, class: "btn btn-primary" %>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#foodsModal">
      Add Ingredients
    </button>
  </div>


  <%= render "food_list_modal", recipe: @recipe, food: @food %>

  <% if flash[:error] %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
  <% end %>
  <%= render("recipe_foods/index", recipe_foods: @recipe_foods) %>


</div>

<script> 
  $(document).on('change', '#flexSwitchCheckDefault', function() {
    $(this).closest('form').submit();
  });
</script>

app/views/shopping_lists/index.html.erb
<h1>Shopping List</h1>
<p>
  <span class="total-items">Amount of food items to buy: <%= @shopping_list.length %></span>
  <span class="total-value">Total value of food needed: <%= @total_value %></span>
</p>
<table class="table">
  <thead>
    <tr>
      <td>Food</td>
      <td>Quantity</td>
      <td>Price</td>
    </tr>
  </thead>
  <tbody>
    <% @shopping_list.each do |ingredient| %>
      <tr>
        <td><%= ingredient[:name] %></td>
        <td><%= ingredient[:quantity] %></td>
        <td><%= ingredient[:price] %></td>
      </tr>
    <% end %>
  </tbody>
</table>